// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iwzjemetiiiqflomwquh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml3emplbWV0aWlpcWZsb213cXVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1MDMxMDEsImV4cCI6MjA3MDA3OTEwMX0.PvJjRMcbOrRb3WMXXwHLmJp6L8lI_SRZ_xeybDhXuWw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});